#!/bin/bash

ROOT=$PWD

set -eu

git clone ${REPO_ROOT} ${REPO_OUT}

if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "${GIT_EMAIL}"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "${GIT_NAME}"
fi

STEMCELL_OS=${STEMCELL_OS:-ubuntu-trusty}
STEMCELL_VERSION=$(cat stemcell/version)

pushd ${REPO_OUT}
  tar -xzf ${ROOT}/compiled-releases/*.tgz $( tar -tzf compiled-releases/*.tgz | grep 'release.MF' )
  RELEASE_NAME=$( grep -E '^name: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  RELEASE_VERSION=$( grep -E '^version: ' release.MF | awk '{print $2}' | tr -d "\"'" )

  RELEASE_URL=$(cat ${ROOT}/compiled-releases/url)
  RELEASE_SHA1=$(sha1sum ${ROOT}/compiled-releases/*.tgz | awk '{print $1}')

  ci/scripts/update-manifest-release $RELEASE_NAME $RELEASE_VERSION $RELEASE_URL $RELEASE_SHA1

  git merge --no-edit ${BRANCH}
  git add -A
  git status
  git commit -m "Updated compiled releases v${RELEASE_VERSION} for ${STEMCELL_OS}/${STEMCELL_VERSION}"
popd
